service: backend-appsync
frameworkVersion: '3'

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs20.x

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'
    - '!package-lock.json'
    - '!package.json'

appSync: ${file(serverless.appsync-api.yml)}